USE [TiendaSara]
GO

/****** Object:  Table [dbo].[CARRITO]    Script Date: 29/06/2025 06:52:41 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CARRITO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FOLIO_VENTA] [int] NOT NULL,
	[TOTAL_COMPRA] [decimal](18, 2) NOT NULL,
	[ESTATUS] [int] NOT NULL,
	[FECHA] [date] NOT NULL,
 CONSTRAINT [PK_CARRITO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


