USE [TiendaSara]
GO

/****** Object:  Table [dbo].[CARRITODETALLES]    Script Date: 29/06/2025 06:53:10 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CARRITODETALLES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_CARRITO] [int] NOT NULL,
	[ID_PRODUCTO] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[SUBTOTAL] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_CARRITODETALLES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CARRITODETALLES]  WITH CHECK ADD  CONSTRAINT [FK_CARRITODETALLES_CARRITO] FOREIGN KEY([ID_CARRITO])
REFERENCES [dbo].[CARRITO] ([ID])
GO

ALTER TABLE [dbo].[CARRITODETALLES] CHECK CONSTRAINT [FK_CARRITODETALLES_CARRITO]
GO

ALTER TABLE [dbo].[CARRITODETALLES]  WITH CHECK ADD  CONSTRAINT [FK_CARRITODETALLES_PRODUCTOS] FOREIGN KEY([ID_PRODUCTO])
REFERENCES [dbo].[PRODUCTOS] ([ID])
GO

ALTER TABLE [dbo].[CARRITODETALLES] CHECK CONSTRAINT [FK_CARRITODETALLES_PRODUCTOS]
GO


